-- NumHunt Leaderboard Table
-- Run this SQL in your Supabase SQL Editor: https://supabase.com/dashboard/project/xirhmfyaywcclhkaugxn/sql

CREATE TABLE IF NOT EXISTS leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  difficulty TEXT NOT NULL DEFAULT 'all',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row-Level Security
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read the leaderboard
CREATE POLICY "Public read access" ON leaderboard
  FOR SELECT USING (true);

-- Allow anyone to insert scores (no auth required for a game)
CREATE POLICY "Public insert access" ON leaderboard
  FOR INSERT WITH CHECK (true);

-- Create index for fast leaderboard queries
CREATE INDEX IF NOT EXISTS idx_leaderboard_score ON leaderboard (score DESC);

-- Optional: limit entries per user to prevent spam (keeps latest 10 per username)
-- You can uncomment this if needed:
-- CREATE OR REPLACE FUNCTION cleanup_old_scores() RETURNS TRIGGER AS $$
-- BEGIN
--   DELETE FROM leaderboard
--   WHERE id IN (
--     SELECT id FROM leaderboard
--     WHERE username = NEW.username
--     ORDER BY created_at DESC
--     OFFSET 10
--   );
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;
-- CREATE TRIGGER limit_scores_per_user
-- AFTER INSERT ON leaderboard
-- FOR EACH ROW EXECUTE FUNCTION cleanup_old_scores();
